package VistaControlador;


public class MonitorVelocidadCrucero extends javax.swing.JPanel {

       public MonitorVelocidadCrucero() {
        initComponents();
        velocidadCrucero.setLcdDecimals(2);
        velocidadCrucero.setLcdUnitString("Km/h");
        setVisible(true);
    }

    public void setVelocidadCrucero(double velocidad){
        velocidadCrucero.setLcdValue(velocidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloCrucero = new javax.swing.JLabel();
        velocidadCrucero = new eu.hansolo.steelseries.gauges.DisplaySingle();

        setOpaque(false);

        tituloCrucero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloCrucero.setForeground(new java.awt.Color(255, 255, 255));
        tituloCrucero.setText("Velocidad de crucero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(velocidadCrucero, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(tituloCrucero)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCrucero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(velocidadCrucero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tituloCrucero;
    private eu.hansolo.steelseries.gauges.DisplaySingle velocidadCrucero;
    // End of variables declaration//GEN-END:variables
}
