package VistaControlador;
import Modelo.velocidad.EstadoMotor;

public class MonitorEstado extends javax.swing.JPanel {

    public MonitorEstado() {
        initComponents();
        actualizarEstado(EstadoMotor.APAGADO);
        setVisible(true);
        
    }

    public void actualizarEstado(EstadoMotor estadoMotor){
        if (estadoMotor == EstadoMotor.ACELERANDO){
            estado.setText("Acelerando");
        } else if (estadoMotor == EstadoMotor.APAGADO){
            estado.setText("Apagado");
        } else if (estadoMotor == EstadoMotor.ENCENDIDO){
            estado.setText("Encendido");
        } else if (estadoMotor == EstadoMotor.FRENANDO){
            estado.setText("Frenando");
        } else if (estadoMotor == EstadoMotor.MANTENIENDO){
            estado.setText("Manteniendo");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);

        estado.setEditable(false);
        estado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        estado.setForeground(new java.awt.Color(255, 255, 255));
        estado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        estado.setBorder(null);
        estado.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField estado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
