package VistaControlador;
import Modelo.velocidad.Vehiculo;


public class Vista extends javax.swing.JPanel {

    private LlaveContactoGUI llave;
    private PedalesGUI pedales;
    private PalancaGUI palanca;
    private Velocimetro velocimetro;
    private Cuentarrevoluciones cuentarrevoluciones;
    private Cuentakilometros cuentakilometros;
    private MonitorEstado monitorEstado;
    private MonitorVelocidadCrucero velocidadCrucero;
    private Vehiculo vehiculo;
    
    public Vista(Vehiculo unVehiculo) {
        vehiculo = unVehiculo;
        llave = new LlaveContactoGUI(vehiculo.getLlaveContacto());
        pedales = new PedalesGUI(vehiculo.getPedales());
        palanca = new PalancaGUI(vehiculo.getPalanca());
        velocimetro = new Velocimetro();
        cuentarrevoluciones = new Cuentarrevoluciones();
        cuentakilometros = new Cuentakilometros();
        monitorEstado = new MonitorEstado();
        velocidadCrucero = new MonitorVelocidadCrucero();
        
        initComponents();
        
        llavePanel.add(llave);
        pedalesPanel.add(pedales);
        palancaPanel.add(palanca);
        cuentaRevolucionesPanel.add(cuentarrevoluciones);
        velocimetroPanel.add(velocimetro);
        cuentaKilometrosPanel.add(cuentakilometros);
        monitorEstadoPanel.add(monitorEstado);
        velocidadCruceroPanel.add(velocidadCrucero);
        
        
        setVisible(true);
    }
    
    public void actualizarVista(){
        palanca.actualizarPosicion();
        llave.actualizarLLaveContacto();
        pedales.actualizarPedales();
        velocidadCrucero.setVelocidadCrucero(vehiculo.getVelocidadCrucero());
        monitorEstado.actualizarEstado(vehiculo.getEstadoMotor().getEstado());
        repaint();
        revalidate();
    }
    
    public PalancaGUI getPalanca(){
        return palanca;
    }
    
    public PedalesGUI getPedales(){
        return pedales;
    }
    
    public LlaveContactoGUI getLlaveContacto(){
        return llave;
    }
    
    public Velocimetro getVelocimetro(){
        return velocimetro;
    }
    
    public Cuentakilometros getCuentakilometros(){
        return cuentakilometros;
    }
    
    public Cuentarrevoluciones getCuentarrevoluciones(){
        return cuentarrevoluciones;
    }
    
    public MonitorEstado getMonitorEstado(){
        return monitorEstado;
    }
    
    public MonitorVelocidadCrucero getMonitorVelocidadCrucero(){
        return velocidadCrucero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pedalesPanel = new javax.swing.JPanel();
        velocimetroPanel = new javax.swing.JPanel();
        cuentaRevolucionesPanel = new javax.swing.JPanel();
        llavePanel = new javax.swing.JPanel();
        palancaPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        algo = new eu.hansolo.steelseries.gauges.Linear();
        velocidadCruceroPanel = new javax.swing.JPanel();
        cuentaKilometrosPanel = new javax.swing.JPanel();
        monitorEstadoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pedalesPanel.setOpaque(false);
        add(pedalesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 487, 244, 174));

        velocimetroPanel.setOpaque(false);
        add(velocimetroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, 366, 343));

        cuentaRevolucionesPanel.setOpaque(false);
        add(cuentaRevolucionesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 397, 343));

        llavePanel.setOpaque(false);
        add(llavePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 393, 229, 82));

        palancaPanel.setOpaque(false);
        add(palancaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 407, 352));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        algo.setLcdVisible(false);
        algo.setLedVisible(false);
        algo.setMajorTickmarkVisible(false);
        algo.setMinorTickmarkVisible(false);
        algo.setTicklabelsVisible(false);
        algo.setTitleVisible(false);

        velocidadCruceroPanel.setOpaque(false);

        cuentaKilometrosPanel.setOpaque(false);

        monitorEstadoPanel.setOpaque(false);

        javax.swing.GroupLayout algoLayout = new javax.swing.GroupLayout(algo);
        algo.setLayout(algoLayout);
        algoLayout.setHorizontalGroup(
            algoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algoLayout.createSequentialGroup()
                .addGroup(algoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(algoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(velocidadCruceroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, algoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(cuentaKilometrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, algoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(monitorEstadoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        algoLayout.setVerticalGroup(
            algoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, algoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cuentaKilometrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(monitorEstadoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(velocidadCruceroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel1.add(algo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 470));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 610, 750));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.Linear algo;
    private javax.swing.JPanel cuentaKilometrosPanel;
    private javax.swing.JPanel cuentaRevolucionesPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel llavePanel;
    private javax.swing.JPanel monitorEstadoPanel;
    private javax.swing.JPanel palancaPanel;
    private javax.swing.JPanel pedalesPanel;
    private javax.swing.JPanel velocidadCruceroPanel;
    private javax.swing.JPanel velocimetroPanel;
    // End of variables declaration//GEN-END:variables
}
